language: generic
sudo: required

services:
    - docker

cache:
    directories:
    - docker_images
    
before_install:
    - docker load -i docker_images/images.tar || true
    - docker build -t rstats-data-mvp:latest .

before_cache:
    - docker save -o docker_images/images.tar $(docker images -a -q)

# script:
#     - docker build --target test --progress=plain -t rstats-data-mvp:latest

# after_success:
#     - docker build --target test --progress=plain -t rstats-data-mvp:test .
