language: generic
sudo: required

services:
    - docker

# cache:
#     directories:
#     - docker_images
    
before_install:
    # - docker load -i docker_images/images.tar || true
    - docker build -t maceapp:latest .

# before_cache:
#     - docker save -o docker_images/images.tar $(docker images -a -q)

# before_cache:
#     # Save tagged docker images
#     - >
#         mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
#         | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

# before_install:
#     # Load cached docker images
#     - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
#     - docker build -t rstats-data-mvp:latest .

# script:
#     - docker build --target test --progress=plain -t rstats-data-mvp:latest

# after_success:
#     - docker build --target test --progress=plain -t rstats-data-mvp:test .
